### ISSUE TITLE
2-4 player

### ISSUE THREAD

**Issue by Vic-ST** [StevenCopeland/Stores#2]
What about we start on the 2-4 player update(@Goredbirds)?

**Comment by ruu5cn** [comment]
I started it on codecademy, but getting money didn't work.
here's the code:
var beginRound2 = function() {
    if (player2.name === "player2") {
        me.name = prompt("What is player1's name?");
        player2.name = prompt("What is player2's name?");
    }
    var buyWorkers = function(ai) {
        if (Math.floor((ai.money - 5)/21) > 0) {
            var toBuy = Math.floor((ai.money - 10)/20);
            var cost = toBuy * 20;
            ai.workers += toBuy;
            ai.money -= cost;
        }
        confirm(ai.name + " bought " + ai.workers + " workers");
    }
    var youBuyWorkers = function(pl) {
        var max = Math.floor(pl.money/20);
        var askP = prompt(pl.name + ", how many workers would you like to
buy? You have " + pl.money + " dollars. The most you can buy is " + max)*1;
        if (pl.money - (askP*20) < 0) {
            confirm("Oops, It looks like you don't have enough money!");
            youBuyWorkers(pl);
        } else if (isNaN(askP)) {
            confirm("Sorry! That's not a number!");
            youBuyWorkers(pl);
        } else {
            var cost = askP*20;
            pl.workers += askP;
            pl.money -= cost;
            confirm(pl.name + " bought " + pl.workers + " workers");
        }
    }
    youBuyWorkers(me);
    youBuyWorkers(player2);
    buyWorkers(ai1);
    buyWorkers(ai2);
    var getMoneyW = function(p) {
        pValue = p.workers * 5 + 5;
        var money1 = rollDice() * pValue;
        p.money += money1;
    }
    var getMoneyM = function(pl) {
        getMoneyW(pl);
        getMoneyW(pl);
        getMoneyW(pl);
        getMoneyW(pl);
        confirm(pl.name + " has " + pl.money);
        pl.workers = 0;
    }
    getMoneyM(me);
    getMoneyM(player2);
    getMoneyM(ai1);
    getMoneyM(ai2);
}

**Comment by ruu5cn** [comment]
do you see anything wrong with it?

**Comment by Vic-ST** [comment]
I think its good.

**Comment by Vic-ST** [comment]
I will open a pull request for the 2-4 players update. Please review it and comment on it.

**Comment by Vic-ST** [comment]
I am now closing this issue
