### ISSUE TITLE
Upgraded workers

### ISSUE THREAD

**Issue by Vic-ST** [StevenCopeland/Stores#22]
We should add upgraded workers because right now it all depends on how many workers you can buy. If you have more money then you are almost certain to win. But if you add upgraded workers then if you are behind then you will be able to get ahead again.

**Comment by Vic-ST** [comment]
Something like: 10 Workers to an Employee, 10 Employees to a Janitor, 10 Janitors to a Boss, 10 Bosses to a CEO, 10 CEOs to a BOD(Board Of Directors). Something like that.

In the immortal words of @StevenCopeland:

> "This will not be easy"

**Comment by StevenCopeland** [comment]
@Stores/the-coding-team we are up for it!

**Comment by Vic-ST** [comment]
@GoRedbirds what do you think?

**Comment by ruu5cn** [comment]
Once again, I don't see how upgraded workers could work. It just seems hard.

**Comment by Vic-ST** [comment]
Its is hard but possible

**Comment by Vic-ST** [comment]
We will do it!

**Comment by Vic-ST** [comment]
This will be closed. I'll open another issue if I think it is worth it.
