### ISSUE TITLE
Address issue found in JavaScript-Files/begin_round.js [Opened by bitHound]

### ISSUE THREAD

**Issue by Vic-ST** [StevenCopeland/Stores#41]
bitHound discovered 1 ComplexFunction in [JavaScript-Files/begin_round.js](https://github.com/StevenCopeland/Stores/blob/c178c7ef2571ec31c3806e378535c1e0a84606fa/JavaScript-Files/begin_round.js). For details go to [bitHound](https://www.bithound.io/github/StevenCopeland/Stores/blob/c178c7ef2571ec31c3806e378535c1e0a84606fa/JavaScript-Files/begin_round.js). 
***
I think we should shorten this function! Any ideas @Goredbirds?
***
Also I finished adding all the players!

**Comment by ruu5cn** [comment]
I think you misunderstood something. Seven players should not be playing at
the same time.

**Comment by Vic-ST** [comment]
Oh........ Great......... Perfect........
Well, then you want me to fix that right? I'll do that a little bit later because I probably need to get off now. I'll fix that.

**Comment by ruu5cn** [comment]
On saturday at codecademy, I'll make the 1-4 player version. Once I'm done with that you can look at the code.

**Comment by Vic-ST** [comment]
Why don't you just fork this and do it here! Also, I will not be on Github all day on Saturday because we have the [ICCFS](http://members.iccinc.org/events/EventDetails.aspx?id=813755&hhSearchTerms=%22Tournaments%22).

**Comment by Vic-ST** [comment]
this issue is now useless
