### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Vic-ST** [StevenCopeland/Stores#50]
There are a lot of since that last pull request so lets fix all those bugs.

Here are some of them:

### HTML
- [x] Change JS links
- [x] Put in new ones
- [x] Delete the old buttons
### JS
- None -
### CSS
- None -

The ones that have none are probably going to change once we complete the ones for HTML because since they are not linked to anything, they will not show any bugs on the page. Any questions? Please comment below.

**Comment by ruu5cn** [comment]
Right now what i'm doing is making my website and finishing the javascript.

**Comment by Vic-ST** [comment]
Okay. If you can send me the list of stuff you told me yesterday then I can do them.

**Comment by Vic-ST** [comment]
I have fixed these bugs and cannot find any new ones(at this time).
