### ISSUE TITLE
Buttons(jQuery)

### ISSUE THREAD

**Issue by Vic-ST** [StevenCopeland/Stores#61]
# Re-Styling buttons:
#### Schedule:
- [x] Try padding 
- [x] Check works
- [x] Try width
- [x] Check works
- [x] Try Height
- [x] Check works

(If one "check works" works than terminate 💯 🥇 👍 ).

**Comment by ruu5cn** [comment]
Look at the website. Now the buttons are too big.

**Comment by Vic-ST** [comment]
Okay. I'll fix that.
